all:Selection_Sort.c
	gcc -o Selection_Sort Selection_Sort.c -Wall -g -std=c99
Bubble_Sort:Bubble_Sort.c
	gcc -o Bubble_Sort Bubble_Sort.c -Wall -g -std=c99
Sequential_Search:Sequential_Search.c
	gcc -o Sequential_Search Sequential_Search.c -Wall -g -std=c99
