all:Selection_Sort.c
	gcc -o Selection_Sort Selection_Sort.c -Wall -g -std=c99
Bubble_Sort:Bubble_Sort.c
	gcc -o Bubble_Sort Bubble_Sort.c -Wall -g -std=c99
Sequential_Search:Sequential_Search.c
	gcc -o Sequential_Search Sequential_Search.c -Wall -g -std=c99
String_Match:String_Match.c
	gcc -o String_Match String_Match.c -Wall -g -std=c99
String_Match_1:String_Match_1.c
	gcc -o String_Match_1 String_Match_1.c -Wall -g -std=c99

